# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/enzo/ProjetSynthese/pds-drone-data-collector

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/enzo/ProjetSynthese/pds-drone-data-collector

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/enzo/ProjetSynthese/pds-drone-data-collector/CMakeFiles /home/enzo/ProjetSynthese/pds-drone-data-collector/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/enzo/ProjetSynthese/pds-drone-data-collector/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named DroneCollector

# Build rule for target.
DroneCollector: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 DroneCollector
.PHONY : DroneCollector

# fast build rule for target.
DroneCollector/fast:
	$(MAKE) -f CMakeFiles/DroneCollector.dir/build.make CMakeFiles/DroneCollector.dir/build
.PHONY : DroneCollector/fast

lib/loguru/loguru.o: lib/loguru/loguru.cpp.o

.PHONY : lib/loguru/loguru.o

# target to build an object file
lib/loguru/loguru.cpp.o:
	$(MAKE) -f CMakeFiles/DroneCollector.dir/build.make CMakeFiles/DroneCollector.dir/lib/loguru/loguru.cpp.o
.PHONY : lib/loguru/loguru.cpp.o

lib/loguru/loguru.i: lib/loguru/loguru.cpp.i

.PHONY : lib/loguru/loguru.i

# target to preprocess a source file
lib/loguru/loguru.cpp.i:
	$(MAKE) -f CMakeFiles/DroneCollector.dir/build.make CMakeFiles/DroneCollector.dir/lib/loguru/loguru.cpp.i
.PHONY : lib/loguru/loguru.cpp.i

lib/loguru/loguru.s: lib/loguru/loguru.cpp.s

.PHONY : lib/loguru/loguru.s

# target to generate assembly for a file
lib/loguru/loguru.cpp.s:
	$(MAKE) -f CMakeFiles/DroneCollector.dir/build.make CMakeFiles/DroneCollector.dir/lib/loguru/loguru.cpp.s
.PHONY : lib/loguru/loguru.cpp.s

src/Main.o: src/Main.cpp.o

.PHONY : src/Main.o

# target to build an object file
src/Main.cpp.o:
	$(MAKE) -f CMakeFiles/DroneCollector.dir/build.make CMakeFiles/DroneCollector.dir/src/Main.cpp.o
.PHONY : src/Main.cpp.o

src/Main.i: src/Main.cpp.i

.PHONY : src/Main.i

# target to preprocess a source file
src/Main.cpp.i:
	$(MAKE) -f CMakeFiles/DroneCollector.dir/build.make CMakeFiles/DroneCollector.dir/src/Main.cpp.i
.PHONY : src/Main.cpp.i

src/Main.s: src/Main.cpp.s

.PHONY : src/Main.s

# target to generate assembly for a file
src/Main.cpp.s:
	$(MAKE) -f CMakeFiles/DroneCollector.dir/build.make CMakeFiles/DroneCollector.dir/src/Main.cpp.s
.PHONY : src/Main.cpp.s

src/drone/Data_Drone.o: src/drone/Data_Drone.cpp.o

.PHONY : src/drone/Data_Drone.o

# target to build an object file
src/drone/Data_Drone.cpp.o:
	$(MAKE) -f CMakeFiles/DroneCollector.dir/build.make CMakeFiles/DroneCollector.dir/src/drone/Data_Drone.cpp.o
.PHONY : src/drone/Data_Drone.cpp.o

src/drone/Data_Drone.i: src/drone/Data_Drone.cpp.i

.PHONY : src/drone/Data_Drone.i

# target to preprocess a source file
src/drone/Data_Drone.cpp.i:
	$(MAKE) -f CMakeFiles/DroneCollector.dir/build.make CMakeFiles/DroneCollector.dir/src/drone/Data_Drone.cpp.i
.PHONY : src/drone/Data_Drone.cpp.i

src/drone/Data_Drone.s: src/drone/Data_Drone.cpp.s

.PHONY : src/drone/Data_Drone.s

# target to generate assembly for a file
src/drone/Data_Drone.cpp.s:
	$(MAKE) -f CMakeFiles/DroneCollector.dir/build.make CMakeFiles/DroneCollector.dir/src/drone/Data_Drone.cpp.s
.PHONY : src/drone/Data_Drone.cpp.s

src/file/Mavlink_file_handler.o: src/file/Mavlink_file_handler.cpp.o

.PHONY : src/file/Mavlink_file_handler.o

# target to build an object file
src/file/Mavlink_file_handler.cpp.o:
	$(MAKE) -f CMakeFiles/DroneCollector.dir/build.make CMakeFiles/DroneCollector.dir/src/file/Mavlink_file_handler.cpp.o
.PHONY : src/file/Mavlink_file_handler.cpp.o

src/file/Mavlink_file_handler.i: src/file/Mavlink_file_handler.cpp.i

.PHONY : src/file/Mavlink_file_handler.i

# target to preprocess a source file
src/file/Mavlink_file_handler.cpp.i:
	$(MAKE) -f CMakeFiles/DroneCollector.dir/build.make CMakeFiles/DroneCollector.dir/src/file/Mavlink_file_handler.cpp.i
.PHONY : src/file/Mavlink_file_handler.cpp.i

src/file/Mavlink_file_handler.s: src/file/Mavlink_file_handler.cpp.s

.PHONY : src/file/Mavlink_file_handler.s

# target to generate assembly for a file
src/file/Mavlink_file_handler.cpp.s:
	$(MAKE) -f CMakeFiles/DroneCollector.dir/build.make CMakeFiles/DroneCollector.dir/src/file/Mavlink_file_handler.cpp.s
.PHONY : src/file/Mavlink_file_handler.cpp.s

src/network/Com_Serial.o: src/network/Com_Serial.cpp.o

.PHONY : src/network/Com_Serial.o

# target to build an object file
src/network/Com_Serial.cpp.o:
	$(MAKE) -f CMakeFiles/DroneCollector.dir/build.make CMakeFiles/DroneCollector.dir/src/network/Com_Serial.cpp.o
.PHONY : src/network/Com_Serial.cpp.o

src/network/Com_Serial.i: src/network/Com_Serial.cpp.i

.PHONY : src/network/Com_Serial.i

# target to preprocess a source file
src/network/Com_Serial.cpp.i:
	$(MAKE) -f CMakeFiles/DroneCollector.dir/build.make CMakeFiles/DroneCollector.dir/src/network/Com_Serial.cpp.i
.PHONY : src/network/Com_Serial.cpp.i

src/network/Com_Serial.s: src/network/Com_Serial.cpp.s

.PHONY : src/network/Com_Serial.s

# target to generate assembly for a file
src/network/Com_Serial.cpp.s:
	$(MAKE) -f CMakeFiles/DroneCollector.dir/build.make CMakeFiles/DroneCollector.dir/src/network/Com_Serial.cpp.s
.PHONY : src/network/Com_Serial.cpp.s

src/threads/Abstract_ThreadClass.o: src/threads/Abstract_ThreadClass.cpp.o

.PHONY : src/threads/Abstract_ThreadClass.o

# target to build an object file
src/threads/Abstract_ThreadClass.cpp.o:
	$(MAKE) -f CMakeFiles/DroneCollector.dir/build.make CMakeFiles/DroneCollector.dir/src/threads/Abstract_ThreadClass.cpp.o
.PHONY : src/threads/Abstract_ThreadClass.cpp.o

src/threads/Abstract_ThreadClass.i: src/threads/Abstract_ThreadClass.cpp.i

.PHONY : src/threads/Abstract_ThreadClass.i

# target to preprocess a source file
src/threads/Abstract_ThreadClass.cpp.i:
	$(MAKE) -f CMakeFiles/DroneCollector.dir/build.make CMakeFiles/DroneCollector.dir/src/threads/Abstract_ThreadClass.cpp.i
.PHONY : src/threads/Abstract_ThreadClass.cpp.i

src/threads/Abstract_ThreadClass.s: src/threads/Abstract_ThreadClass.cpp.s

.PHONY : src/threads/Abstract_ThreadClass.s

# target to generate assembly for a file
src/threads/Abstract_ThreadClass.cpp.s:
	$(MAKE) -f CMakeFiles/DroneCollector.dir/build.make CMakeFiles/DroneCollector.dir/src/threads/Abstract_ThreadClass.cpp.s
.PHONY : src/threads/Abstract_ThreadClass.cpp.s

src/threads/Database_ThreadClass.o: src/threads/Database_ThreadClass.cpp.o

.PHONY : src/threads/Database_ThreadClass.o

# target to build an object file
src/threads/Database_ThreadClass.cpp.o:
	$(MAKE) -f CMakeFiles/DroneCollector.dir/build.make CMakeFiles/DroneCollector.dir/src/threads/Database_ThreadClass.cpp.o
.PHONY : src/threads/Database_ThreadClass.cpp.o

src/threads/Database_ThreadClass.i: src/threads/Database_ThreadClass.cpp.i

.PHONY : src/threads/Database_ThreadClass.i

# target to preprocess a source file
src/threads/Database_ThreadClass.cpp.i:
	$(MAKE) -f CMakeFiles/DroneCollector.dir/build.make CMakeFiles/DroneCollector.dir/src/threads/Database_ThreadClass.cpp.i
.PHONY : src/threads/Database_ThreadClass.cpp.i

src/threads/Database_ThreadClass.s: src/threads/Database_ThreadClass.cpp.s

.PHONY : src/threads/Database_ThreadClass.s

# target to generate assembly for a file
src/threads/Database_ThreadClass.cpp.s:
	$(MAKE) -f CMakeFiles/DroneCollector.dir/build.make CMakeFiles/DroneCollector.dir/src/threads/Database_ThreadClass.cpp.s
.PHONY : src/threads/Database_ThreadClass.cpp.s

src/threads/DroneReceiver_ThreadClass.o: src/threads/DroneReceiver_ThreadClass.cpp.o

.PHONY : src/threads/DroneReceiver_ThreadClass.o

# target to build an object file
src/threads/DroneReceiver_ThreadClass.cpp.o:
	$(MAKE) -f CMakeFiles/DroneCollector.dir/build.make CMakeFiles/DroneCollector.dir/src/threads/DroneReceiver_ThreadClass.cpp.o
.PHONY : src/threads/DroneReceiver_ThreadClass.cpp.o

src/threads/DroneReceiver_ThreadClass.i: src/threads/DroneReceiver_ThreadClass.cpp.i

.PHONY : src/threads/DroneReceiver_ThreadClass.i

# target to preprocess a source file
src/threads/DroneReceiver_ThreadClass.cpp.i:
	$(MAKE) -f CMakeFiles/DroneCollector.dir/build.make CMakeFiles/DroneCollector.dir/src/threads/DroneReceiver_ThreadClass.cpp.i
.PHONY : src/threads/DroneReceiver_ThreadClass.cpp.i

src/threads/DroneReceiver_ThreadClass.s: src/threads/DroneReceiver_ThreadClass.cpp.s

.PHONY : src/threads/DroneReceiver_ThreadClass.s

# target to generate assembly for a file
src/threads/DroneReceiver_ThreadClass.cpp.s:
	$(MAKE) -f CMakeFiles/DroneCollector.dir/build.make CMakeFiles/DroneCollector.dir/src/threads/DroneReceiver_ThreadClass.cpp.s
.PHONY : src/threads/DroneReceiver_ThreadClass.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... DroneCollector"
	@echo "... lib/loguru/loguru.o"
	@echo "... lib/loguru/loguru.i"
	@echo "... lib/loguru/loguru.s"
	@echo "... src/Main.o"
	@echo "... src/Main.i"
	@echo "... src/Main.s"
	@echo "... src/drone/Data_Drone.o"
	@echo "... src/drone/Data_Drone.i"
	@echo "... src/drone/Data_Drone.s"
	@echo "... src/file/Mavlink_file_handler.o"
	@echo "... src/file/Mavlink_file_handler.i"
	@echo "... src/file/Mavlink_file_handler.s"
	@echo "... src/network/Com_Serial.o"
	@echo "... src/network/Com_Serial.i"
	@echo "... src/network/Com_Serial.s"
	@echo "... src/threads/Abstract_ThreadClass.o"
	@echo "... src/threads/Abstract_ThreadClass.i"
	@echo "... src/threads/Abstract_ThreadClass.s"
	@echo "... src/threads/Database_ThreadClass.o"
	@echo "... src/threads/Database_ThreadClass.i"
	@echo "... src/threads/Database_ThreadClass.s"
	@echo "... src/threads/DroneReceiver_ThreadClass.o"
	@echo "... src/threads/DroneReceiver_ThreadClass.i"
	@echo "... src/threads/DroneReceiver_ThreadClass.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

